# title: ""
# url: "https://rabbit-hu.github.io"
# baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

header: no

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "This site uses Jekyll theme: Researcher, under GNU GPL v3."

# sass:
#     style: compressed
#     sass_dir: _sass

# nav:
#  - name: "About"
#    link: "/researcher/"
#  - name: "Resume"
#    link: "resume.pdf"
#  - name: "Contact"
#    link: "contact"
